/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Mock__factory } from "./ERC20Mock__factory";
export { ERC20impl__factory } from "./ERC20impl__factory";
